class custom_exception(Exception):
    pass
